name: Auto Merge

on:
  pull_request_target:
    paths:
      - "package.json"
      - "pnpm-lock.yaml"
      - ".github/workflows/*.yml"

permissions:
  pull-requests: read
  contents: read

jobs:
  merge:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: get Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v2

      - run: |
          echo ${{ steps.dependabot-metadata.outputs }}
          echo "${{ steps.dependabot-metadata.outputs }}" >> $GITHUB_STEP_SUMMARY

      - name: Enable auto-merge for Dependabot PRs
        # if: ${{ steps.dependabot-metadata.outputs.update-type == 'version-update:semver-patch'|| steps.dependabot-metadata.outputs.update-type == 'version-update:semver-minor' }}
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
