name: CI

on:
  push:
    branches:
      - "main"
    paths:
      - "src/**.tsx?"
      - "package.json"
      - "tsconfig.json"
      - ".github/workflows/ci.yml"
  pull_request:
    paths:
      - "src/**.tsx?"
      - "scripts/**"
      - "package.json"
      - "tsconfig.json"
      - ".github/workflows/ci.yml"

env:
  default_node_version: "lts/*"
  default_pnpm_version: "latest"
  artifact_name: build_${{ github.sha }}

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  check-types:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: ${{env.default_pnpm_version}}

      - uses: actions/setup-node@v4
        with:
          node-version: ${{env.default_node_version}}
          cache: pnpm

      - name: Install Dependencies
        run: pnpm i

      - name: Type Check
        run: |
          pnpm run check-types

  lint:
    name: ESLint
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/download-artifact@v5
        with:
          name: ${{ env.artifact_name }}

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: ${{env.default_pnpm_version}}

      - uses: actions/setup-node@v4
        with:
          node-version: ${{env.default_node_version}}
          cache: pnpm

      - name: Install Dependencies
        run: pnpm i

      - name: ESLint
        run: |
          pnpm run lint

  # test:
  #   name: Test
  #   needs:
  #     - build
  #     - check-types
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest, windows-latest, macos-latest]
  #     fail-fast: false
  #   steps:
  #     - uses: actions/checkout@v5

  #     - uses: actions/download-artifact@v5
  #       with:
  #         name: ${{ env.artifact_name }}

  #     - uses: pnpm/action-setup@v4
  #       name: Install pnpm
  #       with:
  #         version: ${{env.default_pnpm_version}}

  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: ${{env.default_node_version}}
  #         cache: pnpm

  #     - name: Install Dependencies
  #       run: pnpm i

  #     - name: Test
  #       run: |
  #         pnpm run test
